### ISSUE TITLE
Conseguir contribuidores pra Megathread

### ISSUE THREAD

**Issue by augustresende** [piratarialink/megathread_pirata#5]

**Comment by augustresende** [comment]
@ubarrawandrey15 @Heus-Sueh @yurirosas @carryingwater @MatadorProBr @einkurogane @winterwulf @biomallard @emanoelhenrick @crzz77 @carolgamaa @jaum20 @otakuprograma2020 @winroque @neozmmv @raveenita @marbovo
 @suportefloripa @GabrielOsvair @BeastMode123456 algum de vocês gostaria de ser adicionado na org para ser contribuidor frequente na megathread?

**Comment by yurirosas** [comment]
A mega vai voltar pro github? Sim, pode me add.

**Comment by augustresende** [comment]
> [yurirosas](/yurirosas)

já voltou

**Comment by neozmmv** [comment]
Eu aceito

**Comment by GabrielOsvair** [comment]
Opa, posso ajudar quando sobrar um tempo sim!

**Comment by augustresende** [comment]
Conseguimos alguns voluntários 👍

**Comment by MatadorProBr** [comment]
Se ainda for possível, tenho interesse em manter a megathread.

**Comment by augustresende** [comment]
Convidado tb!

**Comment by suportefloripa** [comment]
Posso ajudar sim. Tenho tempo 2x por semana.

Em seg., 14 de out. de 2024 12:14, August Resende ***@***.***>
escreveu:

**Comment by jaum20** [comment]
Pode add

**Comment by augustresende** [comment]
Adicionados, aceitem em https://github.com/piratarialink

**Comment by carolgamaa** [comment]
Posso contribuir nas horas vagas
